version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minigithub
    depends_on:
      - db
    ports:
      - 8085:8080
    restart: always

  db:
    image: 'postgres:14.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=minigithub
    ports:
      - 5431:5432