spring:
  profile:
    active: dev
  datasource:
    driverCLassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/minigithub
    username: postgres
    password: 12345
  jpa:
    hibernate.ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
  main:
    allow-circular-references: true